kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: himu                 
spec:                                    
  containers:                      
    - name: himu
      image: ubuntu              
      command: ["/bin/bash", "-c", "while true; do echo Himanshu; sleep 5 ; done"]
