apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    myname: suraj
  template:
    metadata:
      name: testpod6
      labels:
        myname: suraj
    spec:
      containers:
      - name: himu
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo suraj; sleep 5; done"]


